Create Order
AngelicaLira/projeto_moip pull request #3
Opened 2018-01-30 17:54 UTC by iandro

2018-02-06 11:23 UTC, mbnakaya requested changes

2018-02-06 11:23 UTC, MbNakaya commented on src/main/java/Orders.java
> +        Order order = new Order();
Acredito que você poderia encapsular essa referência dentro da criação do pedido (um mero detalhe). Por exemplo:
```java
Order createdOrder = api.order().create(new OrderRequest()
  .ownId("order_own_id")
  .addItem("Nome do produto", 1, "Mais info...", 100)
  .customer(new CustomerRequest()
    .ownId("customer_own_id")
// ...
```

2018-02-06 11:23 UTC, MbNakaya commented on projeto_moip.iml
> +</module>
Não é necessário enviar esse arquivo `.iml` para o projeto. Você pode adicionar `*.iml` no arquivo `.gitignore`, para resolver isso.

2018-02-06 11:49 UTC, mbnakaya requested changes

2018-02-06 11:49 UTC, MbNakaya commented on src/main/java/Orders.java
> +        return order;
Se o objeto `Order` está sendo retornado, é realmente necessário _printar_ esse objeto sempre que o método for chamado?

2018-02-06 11:49 UTC, MbNakaya commented on src/main/java/Orders.java
> +    public void getOrder(String id) {
Deixando o método como `void`, o usuário não terá nenhum acesso ao objeto ou qualquer variável que ele possua (id, ownId, amount, etc), apenas terá as informações _printadas_ na tela.

2018-02-15 17:02 UTC, mbnakaya requested changes

2018-02-15 17:02 UTC, MbNakaya commented on src/main/java/Orders.java
> +        // Customer Shipping Address Zip
@AngelicaLira, o ideal seria que todos estes comentários mantivessem o mesmo padrão. Se verificar o modo como os comentários foram escritos na classe **Customers**, verá que o padrão é diferente. Recomendo manter o padrão da classe **Customers**, já que esta foi mergeada. Se optarem por trocar o padrão de comentários, podem fazê-lo em outro PR. 😉

2018-02-15 17:02 UTC, MbNakaya commented on src/main/java/Orders.java
> +        System.out.println("\n Digite o Código Moip do pedido:");
Acho que seria melhor `"\nDigite o ID Moip do Order:"`, mantendo o padrão do que foi feito em **Customers**.

2018-02-15 20:21 UTC, AngelicaLira commented
Corrigido e reenviado Matheus

2018-02-16 13:27 UTC, mbnakaya submitted a review, later dismissed

2018-02-19 20:30 UTC, mbnakaya approved these changes

2018-02-19 20:30 UTC, merged